### PR TITLE
Trigger CI

### LINKED ISSUE #4: Missing linux build
Version 1.0.4 is not built for linux: https://anaconda.org/conda-forge/lzstring/files 

This is the first version to be built for py3.7, preventing from upgrading to py3.7 for all packages that depend on lzstring.

### PR DESCRIPTION
**Pull request by vladsavelyev**
Attempt to re-trigger CircleCI to fix https://github.com/conda-forge/lzstring-feedstock/issues/4

### CODE REVIEW

**Comment by vladsavelyev** [comment]
Errors aside, It didn't attempt to start CircleCI at all. No idea why...

**Comment by dbast** [comment]
@conda-forge-admin, please re-render

**Comment by dbast** [comment]
re-rendered -> more is triggered now :)

**Comment by dbast** [comment]
@conda-forge-admin, please add noarch: python

**Comment by dbast** [comment]
Looks like noarch could be possible? let's see if it builds.

**Comment by ewels** [comment]
🧙🏻‍♂️ Absolute magic! Thanks @dbast!

**Comment by dbast** [comment]
I think this is ready to be merged.

**Comment by vladsavelyev** [comment]
That's awesome, fascinating to see how automated is it. Don't tell robots can merge too!

**Pull request merged**
